# Generated by Django 4.0.5 on 2022-06-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=20, null=True)),
                ('uf', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.TextField()),
                ('endereco', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('descricao_ingles', models.TextField(max_length=200, null=True)),
                ('slogan', models.TextField(max_length=100, null=True)),
                ('ponto_contato', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.BigIntegerField()),
                ('ident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.TextField()),
                ('ident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emp.empresa')),
            ],
        ),
    ]
